---
title: "Homework"
---

A weekly problem set will be made available after class on Tuesday, due before the start of class on the following Tuesday Some time each week will be devoted to collaborative coding components of the assignment. Problem sets must be completed as a .Rmd file in RStudio and submitted via GitHub. 


## Submission Instructions

1. Use the link sent to your Grinnell email to accept the assignment and automatically create a corresponding repository in the [class Github organization](https://github.com/Grinnell-STA-295-S24).

2. Clone your repo to your directory on the Grinnell RStudio server or to your personal computer. 

3. Complete all problems indicated in the assignment in the supplied .Rmd file. Commit often!

4. Frequently knit your .Rmd file into a .pdf to view the polished product. Make sure you knit one final time before submitting your assignment.

5. When you are ready to submit your assignment, push all commits to both your .Rmd and your .pdf file to your repo on the [class Github organization](https://github.com/Grinnell-STA-295-S24) before the assignment deadline. 

6. Navigate to your repo on the class organization and review your .Rmd and .pdf files. What you see in this repo is what will be graded.

7. Feedback on the assignment will available in a pull request which was opened automatically when your assignment repo was created. You will receive email notification once comments have been made. To view the pull request, navigate to your repo on the [class Github organization](https://github.com/Grinnell-STA-295-S24), or follow the original link you used to accept the assignment.

## Grading Rubric

Most homework problems will be graded out seven points, with five points for statistical content, and two points for the quality of writing and clarity of code.



| Statistical Content | Criteria |
|:-:|--------|
| 5 | The solution is correct and complete. |
| 4 | The solution is mostly correct, except for some small error. Or it may be missing a small but essential component. |
| 3 | The solution is partially correct, but overlooks a moderate component of the problem, or makes a moderate mistake. |
| 2 | The solution is incorrect, but contains important ideas. It may overlook multiple moderate components, or make a significant mistake. |
| 1 | The solution is incorrect, but contains some relevant ideas. Alternatively, the solution briefly indicates the correct answer, but provides no further justification. |
| 0 | Either the solution is missing entirely, or contains very limited progress towards a final answer. |
| +0.5 | Half points may be awarded for solutions that fall between two of the above levels. |
 
| Code Clarity | Criteria |
|:-:|--------|
| 2 | The solution is well-written and code is efficient and easy to read. |
| 1 | Writing has some errors or ambiguity; or code is not efficient or clear |
| 0 |  Writing has significant errors or is very difficult to understand; code cannot be deciphered, or accomplished task in extremely inefficient way |
| +0.5 | Half points may be awarded for solutions that fall between two of the above levels. |
 